# Generated by Django 4.2.6 on 2024-02-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'verbose_name': 'AccountBalance', 'verbose_name_plural': 'AccountBalance'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transaction'},
        ),
    ]
