# Generated by Django 4.2.6 on 2024-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_accountbalance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='Balance',
            new_name='balance',
        ),
    ]
